### ISSUE TITLE
End goal language support

### ISSUE THREAD

**Issue by lastmjs** [web-devkits/Wasmnizer-ts#13]
Is the end goal support for the full TypeScript language? What about JavaScript?

**Comment by xujuntwt95329** [comment]
Hi, we are trying to support more language features, but since WebAssembly opcode is statically compiled, a full-set of TypeScript seems not possible. e.g.:
- `eval`
- function bind

For `JavaScript`, it's not in scope of `Wasmnizer-ts`. In `Wasmnizer-ts` we are trying to use the type information in source code to do static compilation, the more type information in the source code, the better performance for the generated wasm module. But `JavaScript` actually contains no type information, then `Wasmnizer-ts` can't get any information for static compilation.

For executing pure JavaScript in WebAssembly, maybe the `VM-in-VM` approach (build a JavaScript VM to WebAssembly) is more suitable
