### ISSUE TITLE
Windows installation 

### ISSUE THREAD

**Issue by louisvangeldrop** [web-devkits/Wasmnizer-ts#41]
Unable to install iwasm_gc under Windows.

**Comment by louisvangeldrop** [comment]
Error:
 -- Build files have been written to: C:/Users/louis/projecten/Wasmnizer-ts/runtime-library/build
make: *** No targets specified and no makefile found.  Stop.

**Comment by xujuntwt95329** [comment]
Hi, Thanks for reporting this issue, I've tried to build iwasm_gc on windows, but I got lots of errors inside QuickJS.
We use QuickJS to deal with the dynamic objects, but seems it's not ready for windows platform.

We may need some time to enable the windows build, I'll reply here once it's finished.

BTW, Would you mind to share use your use case on windows?

**Comment by louisvangeldrop** [comment]
I am using Windows, because I own a PC running Windows. My intention is to use  WASM/WASI as a platform for my IOT activities. 
As MCU I am running the ESP32-Cx boards and I hope that this solution offers me the opportunity to write all software including drivers in Typescript. There are other Javascript-based platforms available, but very often for driver you need a C++/C solution. However I am little bit nervous that the Quickjs software is taking a lot of the RAM-resources of a ESP32-Cx.

**Comment by louisvangeldrop** [comment]
Is it an option to make an installation ts2wasm using npm like in the bytealliance/javy project? Javy also includes the Quickjs software.

**Comment by xujuntwt95329** [comment]
> I am using Windows, because I own a PC running Windows. My intention is to use WASM/WASI as a platform for my IOT activities. As MCU I am running the ESP32-Cx boards and I hope that this solution offers me the opportunity to write all software including drivers in Typescript. There are other Javascript-based platforms available, but very often for driver you need a C++/C solution. However I am little bit nervous that the Quickjs software is taking a lot of the RAM-resources of a ESP32-Cx.

Hi, really glad to know that you are interested in this project! Actually one of the biggest goal of Wasmnizer-ts is to provide a both `development efficient` and `execution efficient` language to the IoT ecosystems, and `TypeScript` is selected because it has simple syntax and a large amount of developers.

As for QuickJS, I fully understand and agree with your concern, in our `iwasm_gc` we use QuickJS to deal with the dynamic objects, but it is not mandatory. Our strategy is: 
- Apply static compilation as much as possible, so the statically known types such as number, boolean, class and so on are all statically compiled and they don't rely on an external JavaScript engine like QuickJS.
- For those dynamic types such as `any`, `union`, we introduced a series of APIs (named `libdyntype`), any operation to these dynamic values will be compiled to API invoke to `libdyntype` APIs. The `iwasm_gc` implement `libdyntype` based on `QuickJS` for convenience, but you can also implement these APIs without QuickJS. So QuickJS is not a problem.

If you really don't need any dynamic features, you can implement empty `libdyntype` stubs, then dynamic values will not work.
If you just need very limited dynamic features, you can implement `libdyntype` APIs with some very simple code (e.g. hash table)

As for the driver development, this is more related to the APIs between the border of wasm and native, to manage the hardware peripherals WebAssembly module must invoke some APIs exposed by the host, so the biggest problem is: which APIs will be exposed? Currently there are [wasi-i2c](https://github.com/WebAssembly/wasi-i2c), [wasi-spi](https://github.com/WebAssembly/wasi-spi), [wasi-digital-io](https://github.com/WebAssembly/wasi-digital-io) proposals, I know these are not enough for driver development, but it's a good start.

However, the bad news it that those proposals are still in very early stage, so at this moment you may need to define your own API set to be exposed to wasm for driver development.

There may also be other problems with driver development (I'm not familiar with driver development, maybe my concern is not necessary) :
1. The `Wasmnizer-ts` leverages WasmGC, the objects are GC managed, I'm not sure if GC is acceptable in driver development
2. WebAssembly currently doesn't define how to enter and recover from an interrupt context, so if you want to call into WebAssembly function in an interrupt context, you must understand some details about the internals to avoid data overwrite. We can have further discussion about this if you are interested.

It's exciting to know that you want to use wasm in IoT world, and we are happy to provide support if you encounter any problems or have any feature requests during using this project.

**Comment by xujuntwt95329** [comment]
> Is it an option to make an installation ts2wasm using npm like in the bytealliance/javy project? Javy also includes the Quickjs software.

There will eventually be a package available on npm, but currently `Wasmnizer-ts` is under active development, we want to publish the npm package after we have a first release.

**Comment by mvadari** [comment]
> we want to publish the npm package after we have a first release

When is a first release planned?

> If you really don't need any dynamic features, you can implement empty libdyntype stubs, then dynamic values will not work.
If you just need very limited dynamic features, you can implement libdyntype APIs with some very simple code (e.g. hash table)

Will there be an option to remove QuickJS from the build and automatically do all this?

**Comment by louisvangeldrop** [comment]
I'm afraid that the project is "dead", maybe due to Intel restructuring the organisation and priorities.

**Comment by xujuntwt95329** [comment]
> > we want to publish the npm package after we have a first release
> 
> When is a first release planned?
> 
> > If you really don't need any dynamic features, you can implement empty libdyntype stubs, then dynamic values will not work.
> > If you just need very limited dynamic features, you can implement libdyntype APIs with some very simple code (e.g. hash table)
> 
> Will there be an option to remove QuickJS from the build and automatically do all this?

Hi, @mvadari thanks for using this project. Due to some priority change, currently we have limited resource on this project, so I'm afraid there is no clear timeline at this moment. But if you have real use case or requirement, we'd like to help.

On the other hand, we meet a problem in the real world usage —— it's very hard to adaptor native APIs to be used by the TypeScript source code, thus requiring a significant amount of work to develop APIs to be used by the applications. This is a common problem in the WebAssembly world, so we hope we can work out a better API solution before the next step of this project.

For removing QuickJS from build, actually we have a simplified libdyntype implementation without QuickJS, you can build with this version through cmake variable `-DUSE_SIMPLE_LIBDYNTYPE=1`. The implementation is [here](https://github.com/web-devkits/Wasmnizer-ts/tree/main/runtime-library/libdyntype/dynamic-simple).

**Comment by louisvangeldrop** [comment]
If I use the -DUSE_SIMPLE_LIBDYNTYPE=1 option will it imply that there is no need anymore to build a specific version of iwasm and wamrc?
